---
- debug:
    msg: "System Will be installing base packages"
    
- name: Install base packages
  become: true
  apt:
    name:
      - ncdu
      - wget
      - curl
      - net-tools
      - wireshark 
      - nmap 
      - aircrack-ng
    state: present
