---
- name: Converge
  hosts: all
  tasks:
    - name: Update apt repository cache
      apt:
        update_cache: yes

    - name: "Include base_packages"
      include_role:
        name: "base_packages"
