---
- name: Create
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create molecule instance(s)
      docker_container:
        name: xenial
        image: "geerlingguy/docker-ubuntu1604-ansible:latest"
        state: started
    - name: Create molecule instance(s)
      docker_container:
        name: bionic
        image: "geerlingguy/docker-ubuntu1804-ansible:latest"
        state: started
    - name: Create molecule instance(s)
      docker_container:
        name: focal
        image: "geerlingguy/docker-ubuntu2004-ansible:latest"
        state: started
